### ISSUE TITLE
Code suggestions

### ISSUE THREAD

**Issue by dougspeed** [bogdanlab/h2-GRE#1]
Hi, the software works great, thanks very much, it was possible to perform the whole analysis in a few hours. 
A couple of minor issues I found (using 130k individuals and 600k snps);

I had to install fire (as well as python-fire)

I had to use --chr_i (rather than  --chr-i)

I first performed the association testing using PLINK2, but for the final step (estimating snp heritability for each chromosome) got a error whose final line was 
AttributeError: 'DataFrame' object has no attribute 'CHR'
This was because in PLINK2, the association results files have a column called #CHROM not CHR. Therefore, I manually renamed this column. I likewise changed ID to SNP and OBS_CT to NMISS
If I instead used PLINK 1.9 for the association analysis (as suggested), I got this error
    assert((legend['A1'] == sumstats['A1']).all())
AssertionError
I think this was because in association analysis, PLINK1.9 does not automatically use A1 from bim file as the test allele. 

Finally, I guess I can get an overall sd by adding up the variances for each chromosome?

Otherwise, as I say, was very quick and easy to use, thanks

**Comment by KangchengHou** [comment]
Hi @dougspeed ,

Thanks for the interest and these are great suggestions!

We will fix these as follows: 
- update the readme.md to add instructions for installing relevant packages easier.
- I think adding `--keep-allele-order` in PLINK 1.9 will preserve the allele order when doing the association study. I'll try that. if that works, i'll update the document accordingly.
- Yes you are right that adding up the variances for each chromosome gives the overall S.D. we'll add more details on calculating the overall S.D. in the document.

Thanks again for the great suggestions!

**Comment by dougspeed** [comment]
Hi again,
the software worked great once more. Just a small comment. You can use plink2 for the linear regression IF you add the option omit-ref (i.e. plink --linear hide-covar omit-ref ...). Then the allele order is unchanged
Thanks
