### ISSUE TITLE
Reference Panel

### ISSUE THREAD

**Issue by agilly** [bogdanlab/h2-GRE#2]
Hi, 

in the help, you mention that currently, the same individuals must be used to perform the association and the heritability estimation. This is not practical for meta-analyses. Do you plan on adding an option for a reference panel soon?

Thanks,

Arthur

**Comment by KangchengHou** [comment]
Sorry for the long-awaited reply. Unfortunately, GRE method is quite sensitive to reference panel in our experiment, so we still recommend calculating in-sample LD and not for application like meta-analyses. Therefore, currently we don't see the need to provide a reference panel.
